version: '3.7'

services:
    db:
        image: mysql:8.0.32
        restart: always
        # volumes:
        #   - ./data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
            # MYSQL_DATABASE:
            # MYSQL_USER:
            # MYSQL_PASSWORD:
            # MYSQL_ALLOW_EMPTY_PASSWORD:
            # MYSQL_RANDOM_ROOT_PASSWORD:
            # MYSQL_ONETIME_PASSWORD:
            # MYSQL_INITDB_SKIP_TZINFO:

    adminer:
        image: adminer:4.8.1
        restart: always
        ports:
            - 8080:8080
        environment:
            # ADMINER_PLUGINS:
            # ADMINER_DESIGN:
            ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER:-db}
