version: '3.7'

services:
    cassandra-node1:
        image: cassandra:4.1.0
        restart: always
        # volumes:
        #   - ./data:/var/lib/cassandra
        #   - ./custom-cassandra.yaml:/etc/cassandra/cassandra.yaml
        ports:
            - 7000:7000
        healthcheck:
            test: ['CMD-SHELL', '[ $$(nodetool statusgossip) = running ]']
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 20s

    cassandra-node2:
        image: cassandra:4.1.0
        restart: always
        environment:
            CASSANDRA_SEEDS: cassandra-node1
        depends_on:
            cassandra-node1:
                condition: service_healthy
